import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {createHash,createVerify} from 'node:crypto';
import assert from 'node:assert/strict';
import path from 'node:path';
const require=createRequire(import.meta.url),crxRequire=createRequire(require.resolve('crx3'));
const Pbf=crxRequire('pbf').default;
const root=process.cwd(),folder=process.env.ATLAS_RELEASE_DIR||path.join(root,'apps/web');
const manifest=JSON.parse(readFileSync(path.join(root,'apps/extension/manifest.json')));
const file=readFileSync(path.join(folder,process.env.ATLAS_RELEASE_DIR?'atlas-extension.crx':'ext/atlas-extension.crx'));
assert.equal(file.subarray(0,4).toString(),'Cr24');assert.equal(file.readUInt32LE(4),3);
const size=file.readUInt32LE(8);assert.ok(size>0&&size<file.length-12);
const reader=new Pbf(file.subarray(12,12+size));
const header=reader.readFields((tag,obj,p)=>{if(tag===2)obj.proof=p.readMessage((n,proof,r)=>{if(n===1)proof.key=r.readBytes();else if(n===2)proof.signature=r.readBytes();},{});else if(tag===10000)obj.signed=p.readBytes();},{});
assert.equal(Buffer.from(header.proof.key).toString('base64'),manifest.key);
const id=[...createHash('sha256').update(header.proof.key).digest().subarray(0,16).toString('hex')].map(c=>String.fromCharCode(97+parseInt(c,16))).join('');
assert.equal(id,'mjfcgmboaijfcaanepdipbgmipnccnpn');
const sizeBytes=Buffer.alloc(4);sizeBytes.writeUInt32LE(header.signed.length);
const verifier=createVerify('sha256');verifier.update(Buffer.from('CRX3 SignedData\0'));verifier.update(sizeBytes);verifier.update(header.signed);verifier.update(file.subarray(12+size));
assert.ok(verifier.verify({key:Buffer.from(header.proof.key),format:'der',type:'spki'},header.proof.signature),'Invalid CRX signature');
const xml=readFileSync(path.join(folder,'updates.xml'),'utf8');assert.ok(xml.includes(`appid="${id}"`));assert.ok(xml.includes(`version="${manifest.version}"`));
console.log(JSON.stringify({version:manifest.version,id,signature:'valid',updateManifest:'matches',bytes:file.length}));
