#!/usr/bin/env node
// Downloads the brand-type candidates (simulator/brand-type.ts) from Google
// Fonts into simulator/fonts/ and writes simulator/brand-fonts.css, so the
// Storybooks serve their own copies (latin subset, woff2, variable where the
// family has one). All of these are under the SIL Open Font License.
//   /usr/bin/node design-system/scripts/brand-fonts.mjs
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const FAMILIES = [
  'Space+Mono:ital,wght@0,400;0,700;1,400;1,700',
  'Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800',
  'Syne:wght@400..800',
  'Inter:ital,wght@0,100..900;1,100..900',
  'Young+Serif',
  'Instrument+Sans:ital,wght@0,400..700;1,400..700',
  'Instrument+Serif:ital@0;1',
  'Rethink+Sans:ital,wght@0,400..800;1,400..800',
  'Spectral:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500',
  'Geist:wght@100..900',
];
const here = path.resolve(import.meta.dirname, '../simulator');
const out = path.join(here, 'fonts');
// A current Chrome gets woff2 and variable fonts.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

await mkdir(out, { recursive: true });
let css = '/* Generated by scripts/brand-fonts.mjs: the brand-type candidates, latin subset. SIL Open Font License. */\n';
for (const family of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${family}&display=swap`, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${family}: ${res.status}`);
  const text = await res.text();
  // Each face comes once per subset, headed by /* latin */, /* latin-ext */ …
  for (const [, subset, block] of text.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]+\})/g)) {
    if (subset !== 'latin') continue;
    const name = block.match(/font-family: '([^']+)'/)[1];
    const style = block.match(/font-style: (\w+)/)[1];
    const weight = block.match(/font-weight: ([\d ]+);/)[1].trim().replace(' ', '-');
    const url = block.match(/url\((https:[^)]+)\)/)[1];
    const file = `${name.toLowerCase().replace(/ /g, '-')}-${style}-${weight}.woff2`;
    const font = await fetch(url);
    if (!font.ok) throw new Error(`${url}: ${font.status}`);
    await writeFile(path.join(out, file), Buffer.from(await font.arrayBuffer()));
    css += block.replace(url, `./fonts/${file}`).replace(/\n\s*unicode-range:[^;]+;/, '') + '\n';
    console.log(file);
  }
}
await writeFile(path.join(here, 'brand-fonts.css'), css);
