import type { Meta, StoryObj } from '@storybook/react-native-web-vite';
import { FirstScreen } from '../../../../apps/mobile/src/proposals/sign-in/FirstScreen.tsx';
import type { RotatingFont } from '../../../../apps/mobile/src/proposals/sign-in/Headlines.tsx';

// Backdrops: five generated by Codex, five Pritam generated in ChatGPT (PROMPTS.md).
const BACKDROPS = {
  alpineMorning: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/alpine-morning.webp'), alpineGoldenMeadow: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/alpine-golden-meadow.webp'), sunriseAboveClouds: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sunrise-above-clouds.webp'),
  alpineSunbeams: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/alpine-sunbeams.webp'), terraceDusk: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/terrace-dusk.webp'),
  skyCumulus: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-cumulus.webp'), skyGolden: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-golden.webp'), skyAboveClouds: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-above-clouds.webp'), skyAlpine: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-alpine.webp'), meadowSky: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/meadow-sky.webp'),
};

type Args = { look: 'sky' | 'meadow'; font: RotatingFont; objects: boolean; blur: number };
const meta: Meta<Args> = {
  title: 'Proposals/Sign in',
  args: { look: 'sky', font: 'instrument', objects: true, blur: 2 },
  argTypes: {
    look: { control: 'inline-radio', options: ['sky', 'meadow'], description: 'Sky or Meadow (colours for the gradient and buttons)' },
    font: { control: 'select', options: ['instrument', 'dmserif', 'bricolage', 'unbounded', 'syne', 'jakarta'], description: 'Typeface for Rotating finds' },
    objects: { control: 'boolean', description: 'FoundKeep’s 3D objects floating over the backdrop' },
    blur: { control: { type: 'range', min: 0, max: 24, step: 1 }, description: 'Blur on the backdrop photo, in points (0 = sharp)' },
  },
  parameters: { simulator: true, layout: 'fullscreen', session: 'signed-out', route: { pathname: '/sign-in', params: {} },
    docs: { description: { component: 'The first screen: no logo, no bookmark; the words are the design. Pritam liked Rotating finds — its typefaces are compared below. Switch Sky/Meadow in Controls; press ↻ (Remount) to replay. Fonts: Google Fonts, SIL OFL.' } } },
};
export default meta;
type Story = StoryObj<Args>;
// Story names must be literal: Storybook reads them without running the file.
export const RotatingInstrument: Story = { name: 'Rotating finds · Instrument Serif', render: ({ look }) => <FirstScreen look={look} type="rotating" font="instrument" /> };
export const RotatingDMSerif: Story = { name: 'Rotating finds · DM Serif Display', render: ({ look }) => <FirstScreen look={look} type="rotating" font="dmserif" /> };
export const RotatingBricolage: Story = { name: 'Rotating finds · Bricolage Grotesque', render: ({ look }) => <FirstScreen look={look} type="rotating" font="bricolage" /> };
export const RotatingUnbounded: Story = { name: 'Rotating finds · Unbounded', render: ({ look }) => <FirstScreen look={look} type="rotating" font="unbounded" /> };
export const RotatingSyne: Story = { name: 'Rotating finds · Syne', render: ({ look }) => <FirstScreen look={look} type="rotating" font="syne" /> };
export const RotatingJakarta: Story = { name: 'Rotating finds · Plus Jakarta Sans + Caveat', render: ({ look }) => <FirstScreen look={look} type="rotating" font="jakarta" /> };
// Rotating finds over each backdrop; typeface, colours and the objects are switches in Controls.
export const OnAlpineMorning: Story = { name: 'Backdrop · Alpine morning (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.alpineMorning} /> };
export const OnAlpineGoldenMeadow: Story = { name: 'Backdrop · Golden meadow (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.alpineGoldenMeadow} /> };
export const OnSunriseAboveClouds: Story = { name: 'Backdrop · Sunrise above clouds (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.sunriseAboveClouds} /> };
export const OnAlpineSunbeams: Story = { name: 'Backdrop · Sunbeams (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.alpineSunbeams} /> };
export const OnTerraceDusk: Story = { name: 'Backdrop · Terrace at dusk (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.terraceDusk} /> };
export const OnSkyCumulus: Story = { name: 'Backdrop · Cumulus (Codex)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyCumulus} /> };
export const OnSkyGolden: Story = { name: 'Backdrop · Golden hour (Codex)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyGolden} /> };
export const OnSkyAboveClouds: Story = { name: 'Backdrop · Above the clouds (Codex)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyAboveClouds} /> };
export const OnSkyAlpine: Story = { name: 'Backdrop · Alpine sky (Codex)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyAlpine} /> };
export const OnMeadowSky: Story = { name: 'Backdrop · Meadow (Codex)', render: a => <FirstScreen look={a.look} type="rotating" font={a.font} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.meadowSky} /> };
export const Highlighter: Story = { name: 'Other · Highlighter', render: ({ look }) => <FirstScreen look={look} type="highlighter" /> };
export const Tags: Story = { name: 'Other · Tags', render: ({ look }) => <FirstScreen look={look} type="tags" /> };
export const Stack: Story = { name: 'Other · Big stack', render: ({ look }) => <FirstScreen look={look} type="stack" /> };
