import type { Meta, StoryObj } from '@storybook/react-native-web-vite';
import { Image, ScrollView, StyleSheet, Text, View, type ImageSourcePropType } from 'react-native';
import { FINDS, FirstScreen as Screen, type Find } from '../../../../apps/mobile/src/proposals/sign-in/FirstScreen.tsx';

// The floating elements on the locked first screen (2026-10-01): every
// candidate, so Pritam can pick, and the ways they could keep moving. Two
// families: FoundKeep's own 3D studio renders (design-system/assets-3d) and
// GPT-6 Astra images (assets/images/element-candidates/gpt, with their prompts).
type Candidate = { name: string; family: '3D studio' | 'GPT-6 Astra'; source: ImageSourcePropType };
const STUDIO: Candidate[] = [
  { name: 'Photo', source: require('../../../../apps/mobile/assets/images/finds/photo.webp') },
  { name: 'Post', source: require('../../../../apps/mobile/assets/images/finds/post.webp') },
  { name: 'Voice memo', source: require('../../../../apps/mobile/assets/images/finds/voice.webp') },
  { name: 'Sparkles', source: require('../../../../apps/mobile/assets/images/finds/sparkles.webp') },
  { name: 'Highlight', source: require('../../../../apps/mobile/assets/images/finds/highlight.webp') },
  { name: 'Folder', source: require('../../../../apps/mobile/assets/images/finds/folder.webp') },
  { name: 'Video', source: require('../../../../apps/mobile/assets/images/finds/video.webp') },
  { name: 'Tag', source: require('../../../../apps/mobile/assets/images/finds/tag.webp') },
  { name: 'Bookmark', source: require('../../../../apps/mobile/assets/images/finds/bookmark.webp') },
  { name: 'Page', source: require('../../../../apps/mobile/assets/images/finds/page.webp') },
  { name: 'Screenshot', source: require('../../../../apps/mobile/assets/images/finds/screenshot.webp') },
  { name: 'Note', source: require('../../../../apps/mobile/assets/images/finds/note.webp') },
  { name: 'PDF', source: require('../../../../apps/mobile/assets/images/finds/pdf.webp') },
  { name: 'Search', source: require('../../../../apps/mobile/assets/images/finds/search.webp') },
].map(c => ({ ...c, family: '3D studio' as const }));
const GPT: Candidate[] = [
  { name: 'Photo', source: require('../../../../apps/mobile/assets/images/element-candidates/gpt/photo.webp') },
  { name: 'Webpage', source: require('../../../../apps/mobile/assets/images/element-candidates/gpt/webpage.webp') },
  { name: 'Voice memo', source: require('../../../../apps/mobile/assets/images/element-candidates/gpt/voice.webp') },
  { name: 'Highlight', source: require('../../../../apps/mobile/assets/images/element-candidates/gpt/highlight.webp') },
  { name: 'Folder', source: require('../../../../apps/mobile/assets/images/element-candidates/gpt/folder.webp') },
  { name: 'Video', source: require('../../../../apps/mobile/assets/images/element-candidates/gpt/video.webp') },
].map(c => ({ ...c, family: 'GPT-6 Astra' as const }));

function Gallery() {
  return <ScrollView contentContainerStyle={styles.page}>
    <Text style={styles.title}>Element candidates</Text>
    <Text style={styles.intro}>Everything that could float around “Keep Every”. Pick the ones you want; the rest go. Shown on the sky they will sit on, at the size they are used.</Text>
    {[{ family: '3D studio', items: STUDIO, note: 'Rendered in FoundKeep’s own three.js studio. On the screen today.' }, { family: 'GPT-6 Astra', items: GPT, note: 'Generated by Codex with GPT-6 Astra: porcelain and thick paper, warm light.' }].map(group => <View key={group.family} style={styles.group}>
      <Text style={styles.family}>{group.family}</Text>
      <Text style={styles.note}>{group.note}</Text>
      <View style={styles.grid}>{group.items.map(item => <View key={item.name} style={styles.tile}>
        <View style={styles.sky}><Image source={item.source} style={styles.img} accessibilityLabel={item.name} /></View>
        <Text style={styles.name}>{item.name}</Text>
      </View>)}</View>
    </View>)}
  </ScrollView>;
}

/** The screen as it is, with GPT-6 Astra's objects where it has them (it has no sparkles or tag). */
const swap: Record<number, ImageSourcePropType> = { 0: GPT[0].source, 1: GPT[1].source, 2: GPT[2].source, 4: GPT[3].source, 5: GPT[4].source, 6: GPT[5].source };
const GPT_FINDS: Find[] = FINDS.map((find, i) => swap[i] ? { ...find, source: swap[i] } : find);

const meta: Meta = { title: 'Proposals/Sign-in elements', parameters: { controls: { disable: true } } };
export default meta;
type Story = StoryObj;
const onScreen = { simulator: true, layout: 'fullscreen', session: 'signed-out', route: { pathname: '/sign-in', params: {} } };
export const Candidates: Story = { name: 'All candidates', render: () => <Gallery />, parameters: { layout: 'fullscreen' } };
export const GptOnScreen: Story = { name: 'On the screen · GPT-6 Astra objects', render: () => <Screen finds={GPT_FINDS} />, parameters: onScreen };
export const MoveDrift: Story = { name: 'Movement · drift (today)', render: () => <Screen movement="drift" />, parameters: onScreen };
export const MoveOrbit: Story = { name: 'Movement · orbit', render: () => <Screen movement="orbit" />, parameters: onScreen };
export const MoveBob: Story = { name: 'Movement · bob and sway', render: () => <Screen movement="bob" />, parameters: onScreen };
export const MoveRise: Story = { name: 'Movement · rise like bubbles', render: () => <Screen movement="rise" />, parameters: onScreen };

const styles = StyleSheet.create({
  page: { padding: 32, gap: 8, maxWidth: 1200 },
  title: { fontSize: 32, fontWeight: '700', letterSpacing: -0.8, color: '#202020' },
  intro: { fontSize: 15, lineHeight: 22, color: '#5c5c5c', maxWidth: 640 },
  group: { marginTop: 24, gap: 6 },
  family: { fontSize: 19, fontWeight: '600', color: '#202020' },
  note: { fontSize: 14, color: '#686868', marginBottom: 6 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  tile: { width: 150, gap: 8 },
  sky: { width: 150, height: 150, borderRadius: 18, backgroundColor: '#2f86d6', alignItems: 'center', justifyContent: 'center' },
  img: { width: 100, height: 100, resizeMode: 'contain' },
  name: { fontSize: 14, fontWeight: '500', color: '#202020' },
});
