import type { Meta, StoryObj } from '@storybook/react-native-web-vite';
import { FirstScreen } from '../../../../apps/mobile/src/proposals/sign-in/FirstScreen.tsx';
import { KEEP_STYLES, type KeepStyle, type Tune } from '../../../../apps/mobile/src/proposals/sign-in/Headlines.tsx';

// Backdrops: five generated by Codex, five Pritam generated in ChatGPT (PROMPTS.md).
const BACKDROPS = {
  alpineMorning: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/alpine-morning.webp'), alpineGoldenMeadow: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/alpine-golden-meadow.webp'), sunriseAboveClouds: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sunrise-above-clouds.webp'),
  alpineSunbeams: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/alpine-sunbeams.webp'), terraceDusk: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/terrace-dusk.webp'),
  skyCumulus: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-cumulus.webp'),
  cumulusTopLight: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-cumulus-top-light.webp'), cumulusTopMedium: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-cumulus-top-medium.webp'), cumulusTopFull: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-cumulus-top-full.webp'), skyGolden: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-golden.webp'), skyAboveClouds: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-above-clouds.webp'), skyAlpine: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/sky-alpine.webp'), meadowSky: require('../../../../apps/mobile/assets/images/sign-in-backgrounds/meadow-sky.webp'),
};

type Args = { look: 'sky' | 'meadow'; keep: KeepStyle; objects: boolean; blur: number } & Tune;
/** The chosen style's sizes, as Controls start them (SF Pro 40 / Caveat 70). */
const CHOSEN: Tune = { leadSize: 40, leadSpacing: -1.2, wordSize: 70, wordSpacing: 0 };
const tuneOf = ({ leadSize, leadSpacing, wordSize, wordSpacing }: Args): Tune => ({ leadSize, leadSpacing, wordSize, wordSpacing });
const meta: Meta<Args> = {
  title: 'Proposals/Sign in',
  args: { look: 'sky', keep: 'hand', objects: true, blur: 1 },
  argTypes: {
    look: { control: 'inline-radio', options: ['sky', 'meadow'], description: 'Sky or Meadow (colours for the gradient and buttons)' },
    keep: { control: { type: 'select', labels: Object.fromEntries(Object.entries(KEEP_STYLES).map(([k, v]) => [k, v.label])) }, options: Object.keys(KEEP_STYLES), description: '“Keep every” and the changing word: SF Pro, with an expressive face for the word' },
    objects: { control: 'boolean', description: 'FoundKeep’s 3D objects floating over the backdrop' },
    blur: { control: { type: 'range', min: 0, max: 24, step: 1 }, description: 'Blur on the backdrop photo, in points (0 = sharp)' },
    leadSize: { name: '“Keep Every” size', control: { type: 'range', min: 24, max: 72, step: 1 }, description: 'Font size of “Keep Every”, in points' },
    leadSpacing: { name: '“Keep Every” letter spacing', control: { type: 'range', min: -4, max: 4, step: 0.1 }, description: 'Letter spacing of “Keep Every”, in points (negative = tighter)' },
    wordSize: { name: 'Word size', control: { type: 'range', min: 36, max: 110, step: 1 }, description: 'Font size of the changing word (Reel, Short, Article…), in points' },
    wordSpacing: { name: 'Word letter spacing', control: { type: 'range', min: -4, max: 6, step: 0.1 }, description: 'Letter spacing of the changing word, in points' },
  },
  parameters: { simulator: true, layout: 'fullscreen', session: 'signed-out', route: { pathname: '/sign-in', params: {} },
    docs: { description: { component: 'The first screen: no logo, no bookmark; the words are the design. The brand face is SF Pro (Apple’s system font); “Keep every” styles pair it with an expressive face for the changing word. Switch Sky/Meadow in Controls; press ↻ (Remount) to replay. Fonts: Google Fonts, SIL OFL.' } } },
};
export default meta;
type Story = StoryObj<Args>;
// Pritam's pick: Codex's Cumulus sky, with clouds added at the top in three strengths.
export const CumulusTopLight: Story = { args: CHOSEN, name: 'Cumulus · clouds on top, light', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.cumulusTopLight} /> };
export const CumulusTopMedium: Story = { args: CHOSEN, name: 'Cumulus · clouds on top, medium', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.cumulusTopMedium} /> };
export const CumulusTopFull: Story = { args: CHOSEN, name: 'Cumulus · clouds on top, full', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.cumulusTopFull} /> };
// "Keep every" styles on the chosen sky. Story names must be literal: Storybook reads them without running the file.
const onCumulus = (a: Args) => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.cumulusTopMedium} />;
export const KeepSerif: Story = { name: 'Keep every · SF Pro + Instrument Serif italic', args: { keep: 'serif' }, render: onCumulus };
export const KeepHand: Story = { name: 'Keep every · SF Pro + Caveat, tilted (chosen)', args: { keep: 'hand', ...CHOSEN }, render: onCumulus };
export const KeepMono: Story = { name: 'Keep every · SF Pro + Space Mono, in a field', args: { keep: 'mono' }, render: onCumulus };
export const KeepSoft: Story = { name: 'Keep every · Instrument Serif + SF Pro Heavy', args: { keep: 'soft' }, render: onCumulus };
export const KeepWeight: Story = { name: 'Keep every · SF Pro only, light over black', args: { keep: 'weight' }, render: onCumulus };
export const KeepPerFind: Story = { name: 'Keep every · a style for each find', args: { keep: 'per-find' }, render: onCumulus };
// Rotating finds over each backdrop; the Keep every style, colours and the objects are switches in Controls.
export const OnAlpineMorning: Story = { name: 'Backdrop · Alpine morning (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.alpineMorning} /> };
export const OnAlpineGoldenMeadow: Story = { name: 'Backdrop · Golden meadow (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.alpineGoldenMeadow} /> };
export const OnSunriseAboveClouds: Story = { name: 'Backdrop · Sunrise above clouds (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.sunriseAboveClouds} /> };
export const OnAlpineSunbeams: Story = { name: 'Backdrop · Sunbeams (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.alpineSunbeams} /> };
export const OnTerraceDusk: Story = { name: 'Backdrop · Terrace at dusk (ChatGPT)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.terraceDusk} /> };
export const OnSkyCumulus: Story = { name: 'Backdrop · Cumulus (Codex)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyCumulus} /> };
export const OnSkyGolden: Story = { name: 'Backdrop · Golden hour (Codex)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyGolden} /> };
export const OnSkyAboveClouds: Story = { name: 'Backdrop · Above the clouds (Codex)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyAboveClouds} /> };
export const OnSkyAlpine: Story = { name: 'Backdrop · Alpine sky (Codex)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.skyAlpine} /> };
export const OnMeadowSky: Story = { name: 'Backdrop · Meadow (Codex)', render: a => <FirstScreen look={a.look} type="rotating" keep={a.keep} tune={tuneOf(a)} objects={a.objects} blur={a.blur} backdrop={BACKDROPS.meadowSky} /> };
export const Highlighter: Story = { name: 'Other · Highlighter', render: ({ look }) => <FirstScreen look={look} type="highlighter" /> };
export const Tags: Story = { name: 'Other · Tags', render: ({ look }) => <FirstScreen look={look} type="tags" /> };
export const Stack: Story = { name: 'Other · Big stack', render: ({ look }) => <FirstScreen look={look} type="stack" /> };
