import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { Capture } from '../../../api/types.ts';
import { Button, Message, Screen } from '../../../components/ui.tsx';
import { captureTitle } from '../../../collection/model.ts';
import { useSession } from '../../../session/SessionProvider.tsx';
import { colors, typography } from '../../../theme.ts';

const readableBytes = (value: number) => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`;
const date = (value?: number | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Unknown';
function Row({ label, value }: { label: string; value?: string | number | null }) { if (value === null || value === undefined || value === '') return null; return <View style={styles.row}><Text style={typography.label}>{label}</Text><Text selectable style={styles.rowValue}>{String(value)}</Text></View>; }

export default function CaptureDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { client, token } = useSession(); const [capture, setCapture] = useState<Capture | null>(null); const [error, setError] = useState('');
  useEffect(() => { let live = true; void client.getCapture(id).then(value => { if (live) setCapture(value.capture); }).catch(value => { if (live) setError((value as Error).message); }); return () => { live = false; }; }, [client, id]);
  const remove = () => Alert.alert('Delete this capture?', 'This permanently removes it from your Foundkeep account.', [{ text: 'Keep it', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await client.deleteCapture(id); router.replace('/(app)/collection'); } catch (value) { setError((value as Error).message); } } }]);
  if (!capture) return <Screen><View style={styles.loading}>{error ? <><Message error>{error}</Message><Button label="Back to collection" secondary onPress={() => router.back()} /></> : <ActivityIndicator color={colors.accent} />}</View></Screen>;
  const source = capture.provenance?.pageUrl || capture.sourceUrl;
  return <Screen><ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" accessibilityLabel="Back to collection" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={21} color={colors.ink} /><Text style={styles.backText}>Collection</Text></Pressable><View style={styles.hero}><Text style={typography.label}>{capture.type}</Text><Text style={typography.title}>{captureTitle(capture)}</Text><Text style={typography.small}>Saved {date(capture.capturedAt)}</Text></View>{source ? <Button label="Open original source" secondary onPress={() => void Linking.openURL(source)} /> : null}{capture.fileName ? <View style={styles.file}><Ionicons name={capture.type === 'audio' ? 'musical-notes-outline' : capture.type === 'video' ? 'videocam-outline' : 'document-outline'} size={28} color={colors.moss} /><View style={{ flex: 1 }}><Text style={styles.fileName}>{capture.fileName}</Text><Text style={typography.small}>{capture.fileMime || 'File'} · {readableBytes(capture.fileBytes)}</Text></View></View> : null}{capture.selectionText ? <Row label="Highlight" value={capture.selectionText} /> : null}{capture.noteText ? <Row label="Note" value={capture.noteText} /> : null}{capture.summary ? <Row label="Summary" value={capture.summary} /> : null}{capture.articleText ? <Row label="Saved text" value={capture.articleText} /> : null}<View style={styles.origin}><Text style={typography.heading}>Original source</Text><Text style={typography.small}>Enough context to trace this item back to where it came from.</Text><Row label="Page" value={source} /><Row label="Canonical page" value={capture.provenance?.canonicalUrl} /><Row label="Publisher" value={capture.provenance?.siteName} /><Row label="Source app" value={capture.provenance?.sourceApplication} /><Row label="Original file" value={capture.provenance?.originalFileName} /><Row label="Declared type" value={capture.provenance?.declaredMime} /><Row label="Original size" value={capture.provenance?.byteSize ? readableBytes(capture.provenance.byteSize) : null} /></View><Message error>{error}</Message><Button label="Delete capture" secondary onPress={remove} /><Text style={styles.authNote}>{capture.fileUrl && token ? 'File access remains private to this connected device.' : ''}</Text></ScrollView></Screen>;
}
const styles = StyleSheet.create({ page: { padding: 22, paddingBottom: 48, gap: 20 }, loading: { flex: 1, justifyContent: 'center', padding: 24, gap: 16 }, back: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 7 }, backText: { color: colors.ink, fontSize: 15, fontWeight: '600' }, hero: { gap: 10, marginBottom: 8 }, file: { flexDirection: 'row', alignItems: 'center', gap: 13, padding: 16, borderWidth: 1, borderColor: colors.line, borderRadius: 10, backgroundColor: colors.surface }, fileName: { color: colors.ink, fontSize: 16, fontWeight: '700' }, row: { gap: 7, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.line }, rowValue: { color: colors.ink, fontSize: 15, lineHeight: 23 }, origin: { gap: 4, padding: 18, borderRadius: 12, backgroundColor: colors.paleMoss }, authNote: { ...typography.small, textAlign: 'center' } });
