import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Brand, Button, Message, Screen } from '../../components/ui.tsx';
import { useSession } from '../../session/SessionProvider.tsx';
import { colors, typography } from '../../theme.ts';

const usage = (value = 0) => `${(value / 1048576).toLocaleString(undefined, { maximumFractionDigits: 1 })} MB`;
export default function Settings() {
  const { account, usage: storage, logout } = useSession(); const [error, setError] = useState('');
  const signOut = () => Alert.alert('Sign out of this iPhone?', 'Foundkeep will stop saving from the Share sheet until you sign in again.', [{ text: 'Stay signed in', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: async () => { try { await logout(); router.replace('/(auth)/welcome'); } catch (value) { setError((value as Error).message); } } }]);
  return <Screen><ScrollView contentContainerStyle={styles.page}><Brand compact /><View style={styles.heading}><Text style={typography.title}>Settings.</Text><Text style={typography.body}>Your account, storage and share connection.</Text></View><View style={styles.panel}><Text style={typography.label}>Signed in as</Text><Text style={styles.account}>{account?.name}</Text><Text style={typography.small}>{account?.email}</Text></View><View style={styles.panel}><Text style={typography.label}>Collection storage</Text><Text style={styles.storage}>{storage?.captures.toLocaleString() || 0} items</Text><Text style={typography.small}>{usage(storage?.bytes)} of {usage(storage?.maxBytes)} used</Text></View><View style={styles.panel}><Text style={typography.label}>Share from any app</Text><Text style={typography.body}>In an iPhone Share menu, choose Foundkeep. If it is hidden, tap More and add it to Favorites.</Text><Text style={typography.small}>Links, text, images, videos, audio, PDFs and other files are supported.</Text></View><Message error>{error}</Message><View style={styles.links}><Button label="Support" secondary onPress={() => void Linking.openURL('https://foundkeep.app/support.html')} /><Button label="Privacy policy" secondary onPress={() => void Linking.openURL('https://foundkeep.app/privacy.html')} /><Button label="Open web dashboard" secondary onPress={() => void Linking.openURL('https://foundkeep.app/dashboard.html')} /></View><Button label="Sign out" secondary onPress={signOut} /><Text style={styles.version}>Foundkeep 1.0.0 · Updates delivered securely through the App Store and EAS Update.</Text></ScrollView></Screen>;
}
const styles = StyleSheet.create({ page: { padding: 22, paddingBottom: 48, gap: 16 }, heading: { gap: 9, marginVertical: 14 }, panel: { gap: 7, padding: 18, borderWidth: 1, borderColor: colors.line, borderRadius: 11, backgroundColor: colors.surface }, account: { color: colors.ink, fontSize: 21, fontWeight: '700' }, storage: { color: colors.ink, fontSize: 23, fontWeight: '700' }, links: { gap: 10 }, version: { ...typography.small, textAlign: 'center', marginTop: 8 } });
