import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Brand, Button, Field, Message, Screen } from '../../components/ui.tsx';
import { useSession } from '../../session/SessionProvider.tsx';
import { colors, typography } from '../../theme.ts';

const usage = (value = 0) => `${(value / 1048576).toLocaleString(undefined, { maximumFractionDigits: 1 })} MB`;
export default function Settings() {
  const { account, usage: storage, policy, updateRequired, logout, deleteAccount } = useSession(); const [error, setError] = useState('');
  const [showDelete, setShowDelete] = useState(false); const [password, setPassword] = useState(''); const [deleting, setDeleting] = useState(false);
  const signOut = () => Alert.alert('Sign out of this iPhone?', 'Foundkeep will stop saving from the Share sheet until you sign in again.', [{ text: 'Stay signed in', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: async () => { try { await logout(); router.replace('/(auth)/welcome'); } catch (value) { setError((value as Error).message); } } }]);
  const confirmDeletion = () => {
    if (!password) { setError('Enter your password to delete this account.'); return; }
    Alert.alert('Permanently delete this account?', 'Every cloud capture and uploaded file will be deleted. This cannot be undone.', [
      { text: 'Keep account', style: 'cancel' },
      { text: 'Delete permanently', style: 'destructive', onPress: () => void (async () => {
        setDeleting(true); setError('');
        try { await deleteAccount(password); router.replace('/(auth)/welcome'); }
        catch (value) { setError((value as Error).message); setDeleting(false); }
      })() },
    ]);
  };
  return <Screen><ScrollView contentContainerStyle={styles.page}><Brand compact /><View style={styles.heading}><Text style={typography.title}>Settings.</Text><Text style={typography.body}>Your account, storage and share connection.</Text></View>{updateRequired ? <Message error>A newer Foundkeep version is required. Update it from the App Store to resume saving.</Message> : <Message>{policy.notice}</Message>}<View style={styles.panel}><Text style={typography.label}>Signed in as</Text><Text style={styles.account}>{account?.name}</Text><Text style={typography.small}>{account?.email}</Text></View><View style={styles.panel}><Text style={typography.label}>Collection storage</Text><Text style={styles.storage}>{storage?.captures.toLocaleString() || 0} items</Text><Text style={typography.small}>{usage(storage?.bytes)} of {usage(storage?.maxBytes)} used</Text></View><View style={styles.panel}><Text style={typography.label}>Share from any app</Text><Text style={typography.body}>In an iPhone Share menu, choose Foundkeep. If it is hidden, tap More and add it to Favorites.</Text><Text style={typography.small}>Links, text, images, videos, audio, PDFs and other files are supported.</Text></View><View style={styles.panel}><Text style={typography.label}>Live configuration</Text><Text style={typography.body}>Policy revision {policy.revision}</Text><Text style={typography.small}>Availability and safe limits sync automatically. App UI and copy can update over the air.</Text></View><Message error>{error}</Message><View style={styles.links}><Button label="Support" secondary onPress={() => void Linking.openURL('https://foundkeep.app/support.html')} /><Button label="Privacy policy" secondary onPress={() => void Linking.openURL('https://foundkeep.app/privacy.html')} /><Button label="Terms" secondary onPress={() => void Linking.openURL('https://foundkeep.app/terms.html')} /><Button label="Open web dashboard" secondary onPress={() => void Linking.openURL('https://foundkeep.app/dashboard.html')} /></View><Button label="Sign out" secondary onPress={signOut} />{showDelete ? <View style={styles.deletePanel}><Text style={typography.heading}>Delete your account?</Text><Text style={typography.small}>This permanently removes every cloud capture, uploaded file, connection, and account credential. Export anything you need first.</Text><Field label="Password" value={password} onChangeText={setPassword} textContentType="password" secureTextEntry autoCapitalize="none" /><Button label="Delete account permanently" danger loading={deleting} onPress={confirmDeletion} /><Button label="Cancel" secondary disabled={deleting} onPress={() => { setShowDelete(false); setPassword(''); setError(''); }} /></View> : <Button label="Delete account" secondary onPress={() => setShowDelete(true)} />}<Text style={styles.version}>Foundkeep 1.0.0 · Updates delivered securely through the App Store and EAS Update.</Text></ScrollView></Screen>;
}
const styles = StyleSheet.create({ page: { padding: 22, paddingBottom: 48, gap: 16 }, heading: { gap: 9, marginVertical: 14 }, panel: { gap: 7, padding: 18, borderWidth: 1, borderColor: colors.line, borderRadius: 11, backgroundColor: colors.surface }, account: { color: colors.ink, fontSize: 21, fontWeight: '700' }, storage: { color: colors.ink, fontSize: 23, fontWeight: '700' }, links: { gap: 10 }, deletePanel: { gap: 12, padding: 18, borderWidth: 1, borderColor: '#D9AAA4', borderRadius: 11, backgroundColor: '#F8EBE8' }, version: { ...typography.small, textAlign: 'center', marginTop: 8 } });
